export const certificates = [
    {
        name: "Modelos Computacionais para Análise de Estruturas",
        organization: "Fórum Civil",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "http://forumcivil.ist.utl.pt/wp-content/uploads/2019/02/cropped-1-1.png",
        pdfUrl: "https://onedrive.live.com/?authkey=%21APxc0a1%5FOWPXz3Y&id=5AE19301F7FCE055%2172137&cid=5AE19301F7FCE055&parId=root&parQt=sharedby&o=OneUp",
        type: "Civil",
        initialDate: "24/05/2007",
        conclusionDate: "24/05/2007",
        duration: "2 hours",
    },
    {
        name: "SAP 2000",
        organization: "CXS Computing - LTI DeCivil IST",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://ingenieriaymas.com/wp-content/uploads/2016/04/sap-2000.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNKjxuex_b_F06S8w?e=gAQe9e",
        type: "Civil",
        initialDate: "03/03/2008",
        conclusionDate: "07/03/2008",
        duration: "16 hours",
    },
    {
        name: "Curso de Iniciação Arquimedes e Cont. Obra",
        organization: "Top Informática - LTI DeCivil IST",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://tienda.seystic.com/wp-content/uploads/2018/02/arquimedes-cype-600x541.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNIoMzieyUuqzDy7w?e=kji4G9",
        type: "Civil",
        initialDate: "29/04/2008",
        conclusionDate: "29/04/2008",
        duration: "8 hours",
    },

    {
        name: "Microsoft Project 2007",
        organization: "Qualicad - LTI DeCivil IST",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://formadoresit.es/wp-content/uploads/2022/02/pngwing.com-3.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNLXt9moKdYmOBJ2w?e=7ZSJx1",
        type: "Civil",
        initialDate: "22/09/2008",
        conclusionDate: "27/09/2008",
        duration: "21 hours",
    },
    {
        name: "Diploma de Registo - Licenciatura em Engenharia Civil",
        organization: "Instituto Superior Técnico",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://th.bing.com/th/id/R.9ce483a576d536ad92d1800e22baedf2?rik=bWjLbTOnw0A6ow&riu=http%3a%2f%2fgroups.ist.utl.pt%2fwwwelab%2fwiki%2fimages%2f8%2f81%2fIst.jpg&ehk=eU0Y%2fjsJmrJ3NCpRKGbFoli%2bYnacC3013EHofIoZB4s%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNNB4C5InYQ1P82RA?e=tlTGmc",
        type: "Civil",
        initialDate: "15/09/2004",
        conclusionDate: "17/07/2009",
        duration: "",
    },
    {
        name: "Avaliação de Bens Imobiliários - Princípios, Organização e Aplicações",
        organization: "FUNDEC - Instituto Superior Técnico",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://th.bing.com/th/id/R.7fb97e4edcb7fe200bde7cd606013236?rik=rAfyNIXZjXstmw&riu=http%3a%2f%2fforumcivil.ist.utl.pt%2fwp-content%2fuploads%2f2014%2f03%2flogo-01-1024x232.png&ehk=AZ5Hk4Xb7khuLA0B8sIue7kPW7TZlC%2b4pgXmmQOOwB0%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNMtPSo3s-AtpXFtw?e=exy0d8",
        type: "Civil",
        initialDate: "04/11/2011",
        conclusionDate: "12/05/2012",
        duration: "190 hours",
    },
    {
        name: "Créditos de Mestrado em Engenharia Civil",
        organization: "Instituto Superior Técnico",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
        "https://th.bing.com/th/id/R.9ce483a576d536ad92d1800e22baedf2?rik=bWjLbTOnw0A6ow&riu=http%3a%2f%2fgroups.ist.utl.pt%2fwwwelab%2fwiki%2fimages%2f8%2f81%2fIst.jpg&ehk=eU0Y%2fjsJmrJ3NCpRKGbFoli%2bYnacC3013EHofIoZB4s%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNOvvoRRiTnSyimlQ?e=nvE1xz",
        type: "Civil",
        initialDate: "",
        conclusionDate: "25/10/2012",
        duration: "",
    },
    
    {
        name: "Créditos de Licenciatura em Engenharia Civil",
        organization: "Instituto Superior Técnico",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://th.bing.com/th/id/R.9ce483a576d536ad92d1800e22baedf2?rik=bWjLbTOnw0A6ow&riu=http%3a%2f%2fgroups.ist.utl.pt%2fwwwelab%2fwiki%2fimages%2f8%2f81%2fIst.jpg&ehk=eU0Y%2fjsJmrJ3NCpRKGbFoli%2bYnacC3013EHofIoZB4s%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNQ_AIvMtJrP2hfTw?e=C7Njsc",
        type: "Civil",
        initialDate: "",
        conclusionDate: "17/07/2009",
        duration: "",
    },
    {
        name: "Changes in Civil Engineering",
        organization: "Ordem dos Engenheiros",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://www.coiias.es/Adjuntos/COIIAS/img/Contenidos/090a8ba3-3fe4-4f3d-8776-ea6e52dfae57/Ordem-dos-Engenheiros-Logo-1-9309%20(1).jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNPcYyKop4XsuPExA?e=cZOhIm",
        type: "Civil",
        initialDate: "31/05/2013",
        conclusionDate: "31/05/2013",
        duration: "2 hours",
    },
    {
        name: "1st BIM International Conference",
        organization: "BIM Forum Portugal",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://danielblazquez.com/wp-content/uploads/2019/03/BIM-Building-Information-Modeling-1165x665.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNRqu7rZ7qtkXz3Og?e=rnURls",
        type: "Civil",
        initialDate: "20/06/2013",
        conclusionDate: "21/06/2013",
        duration: "",
    },
    {
        name: "3º Congresso Nacional sobre Segurança e Conservação de Pontes",
        organization: "ASCP",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://i1.wp.com/ncultura.pt/wp-content/uploads/2015/11/10507111_589090381224654_6051676320260456925_o.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNST0_G8L0ta5U0Qg?e=YQsdQq",
        type: "Civil",
        initialDate: "26/06/2013",
        conclusionDate: "28/06/2013",
        duration: "",
    },
    {
        name: "Synchro Certified User for Synchro Pro 2017",
        organization: "Synchro Software Ltd",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://logodix.com/logo/2168283.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNTqr9u6cqzdeUgRg?e=xLoK71",
        type: "Civil",
        initialDate: "",
        conclusionDate: "14/12/2017",
        duration: "",
    },
    {
        name: "Synchro Certified Advanced User for Synchro Pro 2017",
        organization: "Synchro Software Ltd",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl:
            "https://logodix.com/logo/2168283.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNUFSHxPD1fM2Wp_Q?e=Txh0uE",
        type: "Civil",
        initialDate: "",
        conclusionDate: "22/12/2017",
        duration: "",
    },
    {
        name: "Geração do Modelo BIM e a sua utilização no sector da construção",
        organization: "FUNDEC - Instituto Superior Técnico",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://th.bing.com/th/id/R.7fb97e4edcb7fe200bde7cd606013236?rik=rAfyNIXZjXstmw&riu=http%3a%2f%2fforumcivil.ist.utl.pt%2fwp-content%2fuploads%2f2014%2f03%2flogo-01-1024x232.png&ehk=AZ5Hk4Xb7khuLA0B8sIue7kPW7TZlC%2b4pgXmmQOOwB0%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "",
        type: "Civil",
        initialDate: "10/04/2018",
        conclusionDate: "10/04/2018",
        duration: "7 hours",
    },
    {
        name: "QGis Iniciação",
        organization: "Ordem dos Engenheiros - Região Norte",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl:"https://logodix.com/logo/1941377.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNV_rT5XPptmo66-Q?e=w6FPwg",
        type: "Civil",
        initialDate: "",
        conclusionDate: "16/04/2021",
        duration: "17 hours",
    },
    {
        name: "Manipulação de Imagens de Satélite para Avaliação de Desastres Naturais",
        organization: "Ordem dos Engenheiros - Região Norte",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.693f13bea01e97936f96b743452e9087?rik=FDUSPrwc82yhIQ&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNXz53ZZnMuTjLgRw?e=hYC9n8",
        type: "Civil",
        initialDate: "",
        conclusionDate: "07/05/2021",
        duration: "16 hours",
    },
    {
        name: "Autodesk Revit",
        organization: "Ordem dos Engenheiros - Região Norte",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://knowledgebase.metrotile.co.uk/wp-content/uploads/2019/10/revit-ft.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNY5dQtSnNSAQYf0w?e=aBEHI7",
        type: "Civil",
        initialDate: "",
        conclusionDate: "24/10/2021",
        duration: "90 hours",
    },
    {
        name: "Certidão - Licenciatura em Engenharia Informática",
        organization: "Instituto Politécnico de Beja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://eduportugal.eu/wp-content/uploads/2017/12/estig_ipbeja_logotipo.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNa6_BlkDuPUjnREQ?e=24A2sL",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "07/12/2018",
        duration: "",
    },
    {
        name: "Diploma - Técnico Especialista em Redes e Sistemas Informáticos",
        organization: "IEFP - Instituto de Emprego e Formação, secção Beja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://www.galileo.edu/fisicc/files/2020/08/telecomunicaciones_redes.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNZHWhL1DqOr7fu5g?e=JpnmOS",
        type: "Computer Science",
        initialDate: "02/09/2019",
        conclusionDate: "02/09/2020",
        duration: "",
    }, 
    {
        name: "Coursera Mentor Community and Training Course",
        organization: "Coursera",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://www.logopedia.cl/wp-content/uploads/2020/05/Coursera-logo-square-compressor-600x330.png",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/55AJCHVCTVLC",
        type: "Education",
        initialDate: "",
        conclusionDate: "06/02/2017",
        duration: "15 hours (approximately)",
    },
    {
        name: "Princípios Metodológicos da Programação",
        organization: "EISnt - Engenharia Informática e Sistemas, Novas Tecnologias, Lda",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://blog.bighouseweb.com.br/wp-content/uploads/2022/01/Linguagens-de-programacao-1140x660.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNnKlB0TL1dHiXqQw?e=sBF2Ee",
        type: "Education",
        initialDate: "",
        conclusionDate: "16/03/2021",
        duration: "25 hours",
    },
    {
        name: "Ação de Formação de Estudantes do Ensino Superior",
        organization: "A3ES - Agência de Avaliação e Acreditação do Ensino Superior",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://www.up.pt/fep/media/images/a3es.original.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNpmOWAzKl5ahap6A?e=fFxkJT",
        type: "Education",
        initialDate: "04/02/2019",
        conclusionDate: "04/02/2019",
        duration: "8 hours",
    },
    {
        name: "Teletrabalho",
        organization: "IEFP - Instituto de Emprego e Formação Profisional - secção Beja",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://www.uebyou.pt/wp-content/uploads/2020/04/Imagem-Website-Interna-Noticia-teletrabalho-2.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNq59jr2tyXmEiLEA?e=UWbI2a",
        type: "Education",
        initialDate: "25/05/2022",
        conclusionDate: "07/06/2022",
        duration: "25 hours",
    },
    {
        name: "Certificado de Competências Pedagógicas",
        organization: "IEFP - Instituto de Emprego e Formação Profisional - secção Beja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://wp-media.petersons.com/blog/wp-content/uploads/2019/03/10123432/iStock-946556568.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNr4-t-gAhB-9qJSA?e=kNgxlP",
        type: "Education",
        initialDate: "",
        conclusionDate: "30/09/2022",
        duration: "90 hours",
    },
    
    {
        name: "ERASMUS+ - International Experience in Vaasa",
        organization: "University of Vaasa",
        country: "Finland 🇫🇮",
        class_type: "On-site",
        imgUrl: "https://d30mzt1bxg5llt.cloudfront.net/public/uploads/images/_signatoryLogo/Vaasan-Yliopisto-logo-vaaka.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNsJtFKCTp6r97H2Q?e=pnp1aK",
        type: "International Experience",
        initialDate: "01/08/2014",
        conclusionDate: "28/02/2015",
        duration: "",
    },
    {
        name: "ERASMUS Intensive Programme - Strategic Business Decisions in a Risky and Rapidly Changing Environment",
        organization: "Burgas Free University",
        country: "Bulgaria 🇧🇬",
        class_type: "On-site",
        imgUrl: "https://stuned.eu/wp-content/uploads/2020/03/Logo-BSU-e1639751267552.jpg",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNtAViYaCefe9555w?e=h1UdcG",
        type: "International Experience",
        initialDate: "02/07/2014",
        conclusionDate: "16/07/2014",
        duration: "",
    },
    {
        name: "Athens Program - BME4: Danube Bridges in Budapest",
        organization: "Budapest University of Technology and Economics",
        country: "Hungary 🇭🇺",
        class_type: "On-site",
        imgUrl: "https://aai.tecnico.ulisboa.pt/files/sites/52/athens-network-logo.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNuYVOnQQWdv-h0qg?e=IcdMwa",
        type: "International Experience",
        initialDate: "01/11/2012",
        conclusionDate: "15/11/2012",
        duration: "",
    },
    {
        name: "Inglês Geral - Nível C1",
        organization: "Centro de Línguas e Culturas - IPBeja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://th.bing.com/th/id/OIP.eS713s9DSMdsbJbrUQgD8wHaEL?rs=1&pid=ImgDetMain",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNvBE7Kre7Oh0jHsA?e=ZEQnRf",
        type: "Language Course",
        initialDate: "20/11/2012",
        conclusionDate: "28/02/2013",
        duration: "60 hours",
    },
    
    {
        name: "Alemão - Nível A1",
        organization: "Centro de Línguas e Culturas - IPBeja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://th.bing.com/th/id/OIP.qlE2_vyl3-3eipF3_AyaUgHaEC?rs=1&pid=ImgDetMain",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNw9EkFEF70aTWCWw?e=LiaBJw",
        type: "Language Course",
        initialDate: "15/10/2013",
        conclusionDate: "29/01/2014",
        duration: "60 hours",
    },
    {
        name: "Espanhol",
        organization: "IEFP - Instituto de Emprego e Formação Profissional",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.2c332d8ba2becad16927186e4a00a227?rik=CfTdqMoEj%2f7bNQ&pid=ImgRaw&r=0",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNxl5by-bGsQV8oyA?e=1kAgb7",
        type: "Language Course",
        initialDate: "16/02/2022",
        conclusionDate: "20/04/2022",
        duration: "100 hours",
    },
    {
        name: "PEPAL - Programa de Estágios Profissionais na Administração Local",
        organization: "CIMBAL - Comunidade Intermunicipal do Baixo Alentejo",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://ipdj.gov.pt/documents/20123/79928/6.-Programa-PEPAL.jpg/2d5544d5-98bb-d4ad-056b-696cf520d229?version=1.0&t=1576237008268",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNyc2j9-n7u3uu6Lg?e=g6BkKi",
        type: "Work Experience",
        initialDate: "01/09/2020",
        conclusionDate: "31/08/2021",
        duration: "12 months",
    },
    {
        name: "Modelação 4D",
        organization: "Projecto ZEP - SOMINCOR - Lundin Mining",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://progesys.ca/wp-content/uploads/2020/09/somincor-logo.png",
        pdfUrl: "",
        type: "Work Experience",
        initialDate: "26/11/2017",
        conclusionDate: "26/08/2018",
        duration: "9 months",
    },
    {
        name: "The Bits and Bytes of Computer Networking ",
        organization: "Coursera - Google",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.b92827d53d6a8f48896b1363a534f389?rik=EjuYpnneqTnLww&riu=http%3a%2f%2ftechniblogic.com%2fwp-content%2fuploads%2f2015%2f11%2fGoogle_logo.png&ehk=N6zb0mVvZ9Sb%2b62vSxLoysomkgQgmrm5Zzy5vn%2bY71g%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/BRKM9PTATWFV",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "19/08/2020",
        duration: "25 hours (approximately)",
    },
    
    {
        name: "Crash Course on Python",
        organization: "Coursera - Google",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.b92827d53d6a8f48896b1363a534f389?rik=EjuYpnneqTnLww&riu=http%3a%2f%2ftechniblogic.com%2fwp-content%2fuploads%2f2015%2f11%2fGoogle_logo.png&ehk=N6zb0mVvZ9Sb%2b62vSxLoysomkgQgmrm5Zzy5vn%2bY71g%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/M8HLTSMW3SXN",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "04/08/2020",
        duration: "32 hours (approximately)",
    },
    {
        name: "Technical Support Fundamentals",
        organization: "Coursera - Google",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.b92827d53d6a8f48896b1363a534f389?rik=EjuYpnneqTnLww&riu=http%3a%2f%2ftechniblogic.com%2fwp-content%2fuploads%2f2015%2f11%2fGoogle_logo.png&ehk=N6zb0mVvZ9Sb%2b62vSxLoysomkgQgmrm5Zzy5vn%2bY71g%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/GCLKTU5NQFJU",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "26/07/2020",
        duration: "26 hours (approximately)",
    },
    {
        name: "Python for Data Science, AI & Development",
        organization: "Coursera - IBM",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.386c15cc643288b3c7244ca3926985ed?rik=lbWBepMJpFvqjw&riu=http%3a%2f%2fpluspng.com%2fimg-png%2flogo-ibm-png-ibm-logo-png-4464.png&ehk=IT%2bhXM4qxkEBumBDGD83ElXGXJXWwamtfZcm4e%2bxDvU%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/BVWFMVF23VK5",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "20/02/2020",
        duration: "25 hours (approximately)",
    },
    {
        name: "What is Data Science?",
        organization: "Coursera - IBM",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.386c15cc643288b3c7244ca3926985ed?rik=lbWBepMJpFvqjw&riu=http%3a%2f%2fpluspng.com%2fimg-png%2flogo-ibm-png-ibm-logo-png-4464.png&ehk=IT%2bhXM4qxkEBumBDGD83ElXGXJXWwamtfZcm4e%2bxDvU%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/LZV3WRK6UPRR",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "08/02/2020",
        duration: "11 hours (approximately)",
    },
    {
        name: "Tools for Data Science",
        organization: "Coursera - IBM",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/R.386c15cc643288b3c7244ca3926985ed?rik=lbWBepMJpFvqjw&riu=http%3a%2f%2fpluspng.com%2fimg-png%2flogo-ibm-png-ibm-logo-png-4464.png&ehk=IT%2bhXM4qxkEBumBDGD83ElXGXJXWwamtfZcm4e%2bxDvU%3d&risl=&pid=ImgRaw&r=0",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/MPPGKUWF67ML",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "08/02/2020",
        duration: "18 hours (approximately)",
    },
    {
        name: "Learn Object Oriented PHP by Building a Complete Website",
        organization: "Eduonix",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/OIP.dWouvJbsUAnnZPIbJqX4EAHaDw?rs=1&pid=ImgDetMain",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLN4dioAinBL7z9NvQ?e=DXwwWe",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "13/03/2016",
        duration: "",
    },
    {
        name: "The Arduino Platform and C Programming",
        organization: "Coursera - University of California, Irvine",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://th.bing.com/th/id/OIP.YJcV4Q2L7BBaNPFnhqRCGQHaEH?rs=1&pid=ImgDetMain",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/KX8PCAV8MRR4",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "09/12/2015",
        duration: "12 hours (approximately)",
    },
    {
        name: "Front-End Web UI Frameworks and Tools",
        organization: "Coursera - The Hong Kong University of Science and Technology",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://download.logo.wine/logo/Hong_Kong_University_of_Science_and_Technology/Hong_Kong_University_of_Science_and_Technology-Logo.wine.png",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/A4SWBFJR85M2",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "11/11/2015",
        duration: "27 hours (approximately)",
    },
    {
        name: "HTML, CSS and JavaScript",
        organization: "Coursera - The Hong Kong University of Science and Technology",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://download.logo.wine/logo/Hong_Kong_University_of_Science_and_Technology/Hong_Kong_University_of_Science_and_Technology-Logo.wine.png",
        pdfUrl: "https://www.coursera.org/account/accomplishments/verify/Z3BMRVHWAFUW",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "21/10/2015",
        duration: "14 hours (approximately)",
    }, 
    {
        name: "COMP107x: Introduction to Mobile Application Development using Android",
        organization: "EdX - The Hong Kong University of Science and Technology",
        country: "Portugal 🇵🇹",
        class_type: "Online",
        imgUrl: "https://download.logo.wine/logo/Hong_Kong_University_of_Science_and_Technology/Hong_Kong_University_of_Science_and_Technology-Logo.wine.png",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLNz8OmLooUehmcz3g?e=siqAl0",
        type: "Computer Science",
        initialDate: "",
        conclusionDate: "15/09/2015",
        duration: "",
    },
    {
        name: "Introduction of Microcontrollers Programming in C",
        organization: "Erasmus+ - IPBeja",
        country: "Portugal 🇵🇹",
        class_type: "On-site",
        imgUrl: "https://th.bing.com/th/id/OIP.1DS5YdyJbICZ-mi2EkUjvwHaEK?rs=1&pid=ImgDetMain",
        pdfUrl: "https://1drv.ms/b/s!AlXg_PcBk-FahLN0PvDzg-xxRQwMtQ?e=8QVtLy",
        type: "Computer Science",
        initialDate: "21/05/2014",
        conclusionDate: "21/05/2014",
        duration: "8 hours",
    }, 
    
];
